### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by PAEz** [gerardogc2378/openshift-redis-cart#2]
Im new to all this Openshift so if its just me, sorry bout that ;).
When I try and install it I get this...
```
C:\forum>rhc add-cartridge http://cartreflect-claytondev.rhcloud.com/reflect?git
hub=gerardogc2378/openshift-redis-cart -a forum
The cartridge
'http://cartreflect-claytondev.rhcloud.com/reflect?github=gerardogc2378/openshif
t-redis-cart'
will be downloaded and installed
Adding
http://cartreflect-claytondev.rhcloud.com/reflect?github=gerardogc2378/openshift
-redis-cart
to application 'forum' ...
Failed to execute: 'control start' for
/var/lib/openshift/55be129889f5cfc4b40000f2/redis
/var/lib/openshift/55be129889f5cfc4b40000f2/redis/bin/control: line 66:
redis-server: command not found
/usr/lib/ruby/1.8/erb.rb:701:in `write': Broken pipe (Errno::EPIPE)
        from /usr/lib/ruby/1.8/erb.rb:701:in `print'
        from /usr/lib/ruby/1.8/erb.rb:701:in `run'
        from /usr/bin/erb:132:in `run'
        from /usr/bin/erb:140
Redis failed to start - 127
```

**Comment by azariah001** [comment]
It's not just you get the exact same error when I use the provided install command.

I also get a install script oversize error when pointing directly at the repository soooooo there's that. I'm about to submit a bug for that as well.

You wouldn't happen to be trying to run NodeBB are you?

**Comment by PAEz** [comment]
@azariah001 
> You wouldn't happen to be trying to run NodeBB are you?
hehe, yep!  and still no luck ;( Ive tried so many combinations of cartridges......thinking I might actually have to learn more about how this openshift stuff works ;)

**Comment by PAEz** [comment]
@azariah001 
Got it working!!!! (NodeBB that is) http://nodebb-paez.rhcloud.com/  names prolly gonna change to forum if that links doesnt work.
Try these two.....
https://github.com/icflorescu/openshift-cartridge-nodejs
https://github.com/transformatordesign/openshift-redis-cart

One problem I only just noticed trying to install nodebb was that nodejs wasnt actually finishing its compiling....that prolly caused a bunch of my probs...mainly the liwp not working.
That redis is at 2.8.13 so upto date and is forked off the one recommended.
Hope that helps ya.

**Comment by azariah001** [comment]
You are awesome. Thanks man. That is seriously difficult to find info. Thank you mutchly. I'm now online as well. :grinning:

**Comment by PAEz** [comment]
hehe, pitty I broke mine ;)
I stopped it, changed something, it didnt work, changed it back, and now it wont work, says....
````
5/8 09:24 [325274] - info: NodeBB Ready
5/8 09:24 [325274] - error:  Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at listen (/var/lib/openshift/55c1e1ee89f5cfadf30000c3/app-root/runtime/repo
/src/webserver.js:197:17)
    at /var/lib/openshift/55c1e1ee89f5cfadf30000c3/app-root/runtime/repo/src/web
server.js:57:3
    at EventEmitter.<anonymous> (/var/lib/openshift/55c1e1ee89f5cfadf30000c3/app
-root/runtime/repo/src/emitter.js:17:5)
    at EventEmitter.emit (events.js:104:17)
    at /var/lib/openshift/55c1e1ee89f5cfadf30000c3/app-root/runtime/repo/src/met
a/js.js:190:12
    at FSReqWrap.oncomplete (fs.js:95:15)
5/8 09:24 [325274] - error: NodeBB address in use, exiting...
[cluster] Child Process (325274) has exited (code: 0, signal: null)
````
ohwell, Ill just keep mucking around ;)

**Comment by azariah001** [comment]
I've got a group of just under 60 Linux nuts wanting to get on to this forum so I can't exactly afford to break mine. :stuck_out_tongue:  Gonna slap a theme on it and get my head around the admin interface and we'll be good to go. Hopefully we don't break OpenStack in the process. :stuck_out_tongue:

**Comment by PAEz** [comment]
Cool, always happy to help, especially a fellow Aussie.
Out of interest (mine)....
I changed something coz of similies.
If you add a smillie to a post the image doesnt show up, because its trying to get it from url:8080
If you encounter this and learn how to fix it, please say as Im coming back to this in a week or so (got to get back to working on my webp web accelerator).

**Comment by azariah001** [comment]
Guess what

```
5/8 10:19 [104822] - info: NodeBB Ready
5/8 10:19 [104822] - error:  Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickDomainCallback (node.js:486:13)
5/8 10:19 [104822] - error: NodeBB address in use, exiting...
[cluster] Child Process (104822) has exited (code: 0, signal: null)
```

I broke mine. :/

**Comment by PAEz** [comment]
Here's another option that does things a little different and so far seems good....
https://github.com/ahwayakchih/openshift-nodebb
...just replace the redis cart with the one above.

Think this is the one Ill spend more time learning how it works.
He added some great docs that help aswell.

**Comment by gnoeley** [comment]
Just submitted a pull request which fixes this issue. Versions numbers were still on 2.8 in other scripts so it couldn't find the correct files during setup.

**Comment by Ariamiro** [comment]
I recommend: https://github.com/ranib/openshift-redis-cart

**Comment by Ariamiro** [comment]
Fixed Cartridge:
https://github.com/Ariamiro/openshift-redis-cart
